# Generated by Django 5.0 on 2024-01-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('rooms', models.IntegerField()),
                ('per', models.IntegerField()),
                ('price', models.FloatField()),
                ('about', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
