# Generated by Django 5.0 on 2024-01-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='himg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimg', models.ImageField(upload_to='images/')),
                ('main_img', models.ImageField(upload_to='images/')),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
                ('img5', models.ImageField(upload_to='images/')),
                ('img6', models.ImageField(upload_to='images/')),
                ('img7', models.ImageField(upload_to='images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hotels')),
            ],
        ),
    ]
