# Generated by Django 5.0 on 2024-01-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_himg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himg',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.hotels'),
        ),
    ]
