# Generated by Django 5.0 on 2024-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_feedback_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('availabel_room', models.IntegerField()),
                ('per_person', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price_room', models.FloatField()),
                ('about', models.TextField()),
                ('cover', models.ImageField(upload_to='images')),
                ('other', models.ImageField(upload_to='images')),
            ],
        ),
    ]
