# Generated by Django 5.0 on 2024-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_hotel_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_request',
            name='other',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
