# Generated by Django 5.0 on 2024-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=20),
        ),
        migrations.AddField(
            model_name='hotels',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotels',
            name='state',
            field=models.CharField(default='Gujarat', max_length=20),
        ),
    ]
