# Generated by Django 5.0 on 2024-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_hotels_city_hotels_email_hotels_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254, unique=True),
        ),
    ]
