# Generated by Django 5.0 on 2024-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_hotels_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_request',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
        ),
    ]
