# Generated by Django 5.0 on 2024-03-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='category',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=3),
        ),
    ]
