# Generated by Django 5.0 on 2024-03-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_hotels_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='category',
            new_name='category_in_star',
        ),
    ]
