# Generated by Django 5.0 on 2024-03-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_hotels_is_luxury'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
