# Generated by Django 5.0 on 2024-03-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_hotels_passs'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passs', models.CharField(default=123456, max_length=25)),
            ],
        ),
    ]
