# Generated by Django 5.0 on 2024-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_hotel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_request',
            name='password1',
            field=models.TextField(default='default@mail.com'),
        ),
        migrations.AddField(
            model_name='hotel_request',
            name='password2',
            field=models.TextField(default='default@mail.com'),
        ),
    ]
