# Generated by Django 5.0 on 2024-03-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_booking_price_per_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price_per_room',
            new_name='total_price',
        ),
    ]
