# Generated by Django 5.0 on 2024-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_booking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
