# Generated by Django 5.0 on 2024-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_booking_rooms_back_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='user_name', max_length=50),
        ),
    ]
