# Generated by Django 5.0 on 2024-04-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_request',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='hotel_request',
            name='password2',
        ),
    ]
