# Generated by Django 5.0 on 2024-04-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_request',
            name='other',
        ),
    ]
