# Generated by Django 5.0 on 2024-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_remove_hotels_passs'),
    ]

    operations = [
        migrations.CreateModel(
            name='bhavesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
    ]
