# Generated by Django 5.0 on 2024-04-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_bhavesh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image',
        ),
    ]
