# Generated by Django 5.0 on 2024-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_hotels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='image',
            field=models.ImageField(default='835201.jpg', upload_to='images'),
        ),
    ]
