# Generated by Django 5.0 on 2024-04-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_booking_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='card',
        ),
    ]
