# Generated by Django 5.0 on 2024-04-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_remove_booking_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bhavesh',
        ),
    ]
